cache: bundler
sudo: false
rvm:
  - "2.3.0"
script: bundle exec rake
gemfile:
  - Gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
notifications:
  email: false
